### ISSUE TITLE
機械学習の feature matrix を埋める

### ISSUE THREAD

**Issue by mrkn** [sciruby-jp/survey#1]
[feature matrix](https://docs.google.com/spreadsheets/d/1ErduLY_PZm6Oflt2B8f0atSTIILR_hDLiq0yVofBuN8/edit#gid=0)

**Comment by mrkn** [comment]
こういう感じでまとめたが、結局 Ruby でまともに機械学習をやるには scikit-learn 相当の環境を作りこむ必要があるという結論に達した。

https://docs.google.com/spreadsheets/d/1TZNg9PWXPdYP9JoW2Qni3QxV5w-IHXl0MsEDQOw_e8w/edit?usp=sharing

**Comment by v0dro** [comment]
Are you planning a project similar to sklearn in Ruby? We had a GSOC project but could not select a suitable student. 

In case you are considering this project, we can have a bunch of projects for it in GSOC next year.

**Comment by mrkn** [comment]
@v0dro Yes.  I've started to write scikit-learn like system.
The key point is that all the estimators have unified API.
It realizes the large library ecosystem like those who scikit-learn (or Python) already has.

**Comment by v0dro** [comment]
So from what I know of the Ruby machine learning ecosystem, many of the methods like bayes theorem, linear classifiers and neural networks already exist, but none of them are unified like scikit-learn.

Are you planning create adapters to these libraries and bring them under a unified interface?
